select
    slug,
    name,
    developer,
    url as listing_url,
    website,
    try_cast(rating as double) as rating,
    try_cast(reviews as integer) as review_count,
    price,
    try_strptime(launched, '%B %d, %Y')::date as launched_on,
    cust_data as customer_data_declared,
    store_data as store_data_declared,
    pcd as declares_protected_customer_data,
    categories,
    len(categories) as category_count,
    ai = 'yes' as has_ai_signal,
    pre as prequalify_tier,
    tier,
    nullif(lower(trim(contact_email)), '') as contact_email,
    nullif(split_part(email_confidence, ' ', 1), '') as email_confidence,
    nullif(email_source, '') as email_source,
    verify_result,
    verify_quality,
    try_cast(verify_date as date) as verified_on
from {{ source('app_leads', 'merged') }}
