select
    md5(slug || '|' || dbt_valid_from::varchar) as lead_key,
    slug,
    name,
    developer,
    listing_url,
    website,
    rating,
    review_count,
    price,
    launched_on,
    customer_data_declared,
    store_data_declared,
    declares_protected_customer_data,
    categories,
    category_count,
    has_ai_signal,
    prequalify_tier,
    tier,
    contact_email,
    email_confidence,
    email_source,
    verify_result,
    verify_quality,
    verified_on,
    status,
    dbt_valid_from as valid_from,
    dbt_valid_to as valid_to,
    dbt_valid_to is null as is_current
from {{ ref('snap_leads') }}
